kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: authz-pvc
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "100Mi"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authz-postgres-configuration
  labels:
    app: authz-postgres
data:
  POSTGRES_DB: authz
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authz
  template:
    metadata:
      labels:
        app: authz
    spec:
      volumes:
        - name: authz-postgresdb-storage
          persistentVolumeClaim:
            claimName: authz-pvc
      containers:
        - image: postgres:9.6.3
          name: my-database
          envFrom:
          - configMapRef:
              name: authz-postgres-configuration
          ports:
          - containerPort: 5432
          resources: {}
          volumeMounts:
          - mountPath: "/var/lib/postgresql/data:Z"
            name: authz-postgresdb-storage        
        - name: authz
          env:
            - name: QS_DB
              value: "authz"
            - name: QS_DB_HOST
              value: "localhost"
            - name: QS_DB_PASS
              value: "password"
            - name: QS_DB_PORT
              value: "5432"
            - name: QS_DB_USER
              value: "postgres"
            - name: QS_GRPC_PORT
              value: "10121"
            - name: QS_HTTP_PORT
              value: "10120"
            - name: QS_LOG_LEVEL
              value: "info"
            - name: QS_ZIPKIN_V2_URL
              value: "http://zipkin.istio-system.svc.cluster.local:9411/api/v2/spans"
          image: index.docker.io/cage1016/gokit-istio-security-authz
---
kind: Service
apiVersion: v1
metadata:
  name: authz
spec:
  selector:
    app: authz
  ports:
    - port: 80
      name: http
      targetPort: 10120
    - port: 8000
      name: grpc
      targetPort: 10121
---
apiVersion: v1
kind: Service
metadata:
  name: authz-external
  labels:
    app: authz
spec:
  type: LoadBalancer
  selector:
    app: authz
  ports:
  - port: 7170
    name: http
    targetPort: 10120
  - port: 7171
    name: grpc
    targetPort: 10121